<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[3]=array(2,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[4]=array(2,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[5]=array(0,1,1,'6K++56iL5Lit5b+D');
$cfg_Cs[6]=array(5,1,1,'6K++56iL5YiG57G75LiA');
$cfg_Cs[7]=array(5,1,1,'6K++56iL5YiG57G75LqM');
$cfg_Cs[8]=array(5,1,1,'6K++56iL5YiG57G75LiJ');
$cfg_Cs[9]=array(5,1,1,'6K++56iL5YiG57G75Zub');
$cfg_Cs[10]=array(5,1,1,'6K++56iL5YiG57G75LqU');
$cfg_Cs[11]=array(5,1,1,'6K++56iL5YiG57G75YWt');
$cfg_Cs[12]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[13]=array(0,1,1,'5biI6LWE5LuL57uN');
$cfg_Cs[14]=array(0,17,1,'5bm754Gv54mH');
?>