<div class="art_list not-animated" data-animate="fadeInUp">
            <div class="art_img"><a href='[field:arcurl/]'><img src='[field:litpic/]' width="" /></a></div>
            <div class="art_right">
                <div class="art_title"><a href='[field:arcurl/]' >[field:title/]</a></div>
                <div class="art_author"><span>日期：[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span></div>
                <div class="art_des">[field:description function='cn_substr(@me,250)'/]...</div>
            </div>
          </div>